name: tender620
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  page_view_indicators: ^2.0.0
  shared_preferences: ^2.0.6
  audio_recorder: 0.0.5
  path_provider: ^0.4.1
  flutter_webrtc: ^0.6.3
  cached_network_image: any
  firebase_core: ^1.3.0
  url_launcher: ^5.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  image_picker: ^0.8.0+3
  firebase_storage: ^8.1.3
  progress_dialog: ^1.2.4
  provider: ^5.0.0

  intl: ^0.17.0

  uuid: ^3.0.4
  video_thumbnail: ^0.3.3
  photo_view: ^0.11.1
  video_player: ^2.1.6
  flutter_facebook_login: ^3.0.0
  http: ^0.13.3
  location: ^4.3.0
  latlong: ^0.6.1
  smooth_page_indicator: ^0.2.3
  firebase_messaging: ^10.0.2
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.2.0
  in_app_purchase: ^1.0.5
  flutter_ringtone_player: ^3.0.0
  wakelock: ^0.5.2
  audioplayers:
  permission_handler: ^8.1.1
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/ulistings_icon.png'

