name: tender620
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  page_view_indicators: ^1.3.1
  shared_preferences: ^0.5.8
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  image_picker: ^0.6.5
  firebase_storage: ^5.0.1
  progress_dialog: ^1.2.2
  provider: ^4.0.1
  url_launcher: ^5.5.0
  intl: ^0.16.1
  cached_network_image: ^2.1.0+1
  uuid: ^2.0.4
  video_thumbnail: ^0.2.1
  path_provider: ^1.6.7
  photo_view: ^0.10.0
  video_player: ^1.0.0
  flutter_facebook_login: ^3.0.0
  http: ^0.12.1
  location: ^3.0.0
  latlong: ^0.6.1
  smooth_page_indicator: ^0.2.0
  flutter_webrtc: ^0.4.1
  firebase_messaging: ^7.0.3
  intl_phone_number_input: ^0.5.2+2
  pin_code_fields: ^6.0.1
  in_app_purchase: ^0.3.4+1
  flutter_ringtone_player: ^2.0.0
  wakelock: ^0.2.1+1
  audio_recorder: ^1.0.2
  audioplayers: ^0.16.2
  permission_handler: ^5.0.1+1
  flutter_rating_bar: ^3.0.1+1
  google_maps_flutter: ^1.0.6
  flutter_google_places: ^0.2.6
  google_maps_webservice: ^0.0.17

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/



flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/ulistings_icon.png'

